[source]
type = "N2N"
address = "relays-new.cardano-mainnet.iohk.io:3001"
peers = ["relays-new.cardano-mainnet.iohk.io:3001"]

[enrich]
type = "Sled"
db_path = "./data/sled_db"

[[reducers]]
type = "FullUtxosByAddress"
key_prefix = "full_utxo"
filter = [
  "addr1zxgx3far7qygq0k6epa0zcvcvrevmn0ypsnfsue94nsn3tvpw288a4x0xf8pxgcntelxmyclq83s0ykeehchz2wtspks905plm",
  "addr1zyfk6gn0cp5cmjj4l0dwjp7sf5lgnh7vhy2ttnqgkauu08cj3fjrevh4a4pt4sqm2lsc0avsrezlucp3306a5t7zg0eqtd4xj3",
  "addr1x8rjw3pawl0kelu4mj3c8x20fsczf5pl744s9mxz9v8n7efvjel5h55fgjcxgchp830r7h2l5msrlpt8262r3nvr8ekstg4qrx",
  "addr1xxgx3far7qygq0k6epa0zcvcvrevmn0ypsnfsue94nsn3tfvjel5h55fgjcxgchp830r7h2l5msrlpt8262r3nvr8eks2utwdd",
]

[storage]
type = "Redis"
url = "redis://localhost:6379"

[intersect]
type = "Tip"

[chain]
type = "mainnet"

[policy]
missing_data = "Skip"
